stages:
  - test

test_job:
  stage: test
  image: python:3.9
  before_script:
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - pytest -v
  artifacts:
    when: always
    paths:
      - pytest-report.xml
    reports:
      junit: pytest-report.xml
